# Markdown 渲染 + 代码高亮
[goldmark]
  [goldmark.renderer]
    unsafe = true
    hardWraps = false
  [goldmark.parser]
    autoHeadingID = true
    autoHeadingIDType = "github"
  [goldmark.parser.attribute]
    block = true
    title = true

[tableOfContents]
  startLevel = 2
  endLevel = 4
  ordered = false

[highlight]
  codeFences = true
  guessSyntax = true
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = false
  style = "github"
  tabWidth = 4
